// Auto-generated by: pnpm supabase gen types typescript --linked > types/database.ts
// Run AFTER applying supabase/migrations/001_initial_schema.sql to your Supabase project.
// Until then this is a placeholder so imports don't break.
export type Database = Record<string, unknown>
