// Auto-generated by: pnpm supabase gen types typescript --linked > types/database.ts
// Run this after applying the migration in Task 8.
// Until then this is a placeholder so imports don't break.
export type Database = Record<string, unknown>
