import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const env = Object.fromEntries(readFileSync('/home/freddievong/Paqar/.env.local','utf8').split('\n')
  .map(l => l.match(/^([^#=\s]+)=(.*)$/)).filter(Boolean).map(m => [m[1], m[2]]))
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 390, height: 844 } })
const p = await ctx.newPage()
await p.goto('http://localhost:3000/admin/review', { waitUntil: 'domcontentloaded' })
await p.fill('input[name="secret"]', env.ADMIN_SECRET)
await p.click('button:has-text("Log Masuk")'); await p.waitForTimeout(4000)
await p.goto(process.argv[2], { waitUntil: 'networkidle', timeout: 60000 })
await p.waitForTimeout(2500)
const body = await p.innerText('body')
const i = body.indexOf('KEPUTUSAN PAQAR')
console.log(body.slice(i, i + 300).replace(/\n{2,}/g, '\n').trim())
await b.close()
