import { notFound }             from 'next/navigation'
export const dynamic = 'force-dynamic'
import { Nav }                  from '@/components/layout/Nav'
import { Shell }                from '@/components/layout/Shell'
import { getCheck }             from '@/lib/db/checks'
import { getBuyerReport, setVehicleApiData } from '@/lib/db/buyer-reports'
import { lookupJomCheck, normalisePlate, isJomCheckManual, type JomCheckResult, type JomCheckStatus } from '@/lib/jomcheck'
import { setJomCheckStatus, setJomCheckSuccess, setJomCheckFailed } from '@/lib/jomcheck/db'
import { BuyerReportContent }   from '@/components/report/BuyerReportContent'
import { PaymentForm }          from '@/components/report/PaymentForm'
import { LockedReportPreview }  from '@/components/report/LockedReportPreview'
import { CollapsibleSampleReport } from '@/components/report/CollapsibleSampleReport'
import { FreeResultGate }      from '@/components/report/FreeResultGate'
import { UnderReviewNotice }   from '@/components/report/UnderReviewNotice'
import { ReviewerNote }        from '@/components/report/ReviewerNote'
import { PaidReportCtaTracker } from '@/components/report/PaidReportCtaTracker'
import { BuyerReportPitch }     from '@/components/report/BuyerReportPitch'
import { VehiclePreviewTeaser } from '@/components/report/VehiclePreviewTeaser'
import { mayRenderReport }      from '@/lib/report-release'
import { isAdminAuthenticated } from '@/lib/admin-auth'
import { decrypt }              from '@/lib/crypto'
import { createClient }         from '@/lib/supabase/server'
import { getOrFetchVehicleData }      from '@/lib/db/plate-lookups'
import { getValuationByNvic }         from '@/lib/db/vehicle-valuations'
import { getCachedMarketPrices,
         fetchAndCacheMarketPrices }  from '@/lib/db/market-prices'
import type { CachedMarketPrices }    from '@/lib/db/market-prices'
import { buildMarketModelKeyword }    from '@/lib/market-keyword'
import { AnalyticsEvent }             from '@/components/layout/AnalyticsEvent'
import { AskingPriceForm }            from '@/components/report/AskingPriceForm'
import { MarketPricePoller }          from '@/components/report/MarketPricePoller'
import { ReportFeedback }             from '@/components/report/ReportFeedback'

interface Props {
  params:       { checkId: string }
  searchParams: { claim_token?: string; asking_price?: string; source?: string; admin_preview?: string }
}

export default async function BuyerReportPage({ params, searchParams }: Props) {
  const claimToken = searchParams.claim_token

  type CheckRow = NonNullable<Awaited<ReturnType<typeof getCheck>>>
  let row: CheckRow | null = null

  if (claimToken) {
    row = await getCheck(params.checkId, claimToken)
  }
  // Fallback: if claim_token lookup failed, try auth ownership check
  if (!row) {
    try {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const candidate = await getCheck(params.checkId)
        if (candidate?.check.user_id === user.id) row = candidate
      }
    } catch {
      // non-fatal
    }
  }

  if (!row || row.check.status !== 'complete') notFound()

  const report = await getBuyerReport(params.checkId)
  const isPaid = report?.status === 'paid'
  // Null when the buyer identified the car by brand/model/year (migration 032).
  // Every plate-dependent step below is skipped rather than faked: an empty
  // string here would render "plat " with nothing after it, and would send the
  // provider a lookup for the empty plate.
  const plateEnc = row.check.plate_encrypted
  const plate    = plateEnc ? decrypt(plateEnc as string).toUpperCase() : null
  // What the report calls this car when there is no plate to head it with.
  const carLabel = plate
    ?? [row.check.brand, row.check.model, row.check.year].filter(Boolean).join(' ')
    ?? ''

  // ── Paid, but no human has released it yet ────────────────────────────────
  //
  // THIS RETURNS EARLY ON PURPOSE. "Disemak oleh manusia sebelum dihantar" is
  // only true if an unreviewed report is unreachable, so BuyerReportContent is
  // not rendered hidden, not collapsed and not greyed out — it is never
  // mounted, and none of the work below it runs. Same rule FreeResultGate
  // already applies to the paywall, for the same reason: an ordering held by
  // JSX position is one hurried edit away from being untrue.
  //
  // The draft the reviewer reads is generated by /admin/review, not here.
  //
  // The reviewer is the ONE exception, and it is authenticated server-side.
  // `?admin_preview=1` alone does nothing: isAdminAuthenticated() compares an
  // httpOnly cookie holding sha256(ADMIN_SECRET) with timingSafeEqual, so the
  // flag is a routing hint and the cookie is the authority. Without this the
  // review queue would ask a human to approve a report they cannot read.
  const adminPreview = searchParams.admin_preview === '1' && isAdminAuthenticated()

  if (isPaid && report && !mayRenderReport(report) && !adminPreview) {
    return (
      <>
        <Nav />
        <Shell>
          <AnalyticsEvent event="report_page_viewed" properties={{ is_paid: true, released: false }} />
          <UnderReviewNotice checkId={params.checkId} />
        </Shell>
      </>
    )
  }

  // ── Paid AND released — full report ───────────────────────────────────────
  if ((mayRenderReport(report) || (adminPreview && isPaid)) && report) {
    // Lazy fetch: call VehicleAPI once, store in DB, serve from cache on subsequent views
    let vehicleData = report.vehicleapi_data as Record<string, unknown> | null ?? null
    if (!vehicleData) {
      const apiResult = plate ? await getOrFetchVehicleData(plate) : null
      if (apiResult) {
        const valuation = await getValuationByNvic(
          apiResult.nvic,
          { make: apiResult.make, year: apiResult.registrationYear, model: apiResult.model }
        ).catch(() => null)
        vehicleData = { ...apiResult, valuation: valuation ?? null }
        setVehicleApiData(report.id, vehicleData).catch(() => {}) // non-blocking
      }
    } else if ((vehicleData.valuation as Record<string, unknown> | null)?.familyFloorNewPrice === undefined) {
      // Heal pre-guard valuations: the old exact-NVIC lookup silently failed
      // on duplicate table rows and stored the CHEAPEST fallback variant
      // (a JCW GP frozen as a Clubman). Re-derive once with the fixed
      // lookup and persist; healed rows carry familyFloorNewPrice and skip this.
      const healed = await getValuationByNvic(
        (vehicleData.nvic as string) ?? '',
        {
          make:  (vehicleData.make as string) ?? '',
          year:  (vehicleData.registrationYear as string) ?? '',
          model: (vehicleData.model as string) ?? undefined,
        }
      ).catch(() => null)
      if (healed) {
        vehicleData = { ...vehicleData, valuation: healed }
        setVehicleApiData(report.id, vehicleData).catch(() => {}) // non-blocking
      }
    }

    // JomCheck — lazy lookup, cached after first success, never retried after failure.
    // In manual mode the API is never called: the owner keys results in via
    // /admin/jomcheck and the report shows a "sedang diproses" card until then.
    let jomcheckData:   JomCheckResult | null = null
    let jomcheckStatus: JomCheckStatus = (report.jomcheck_status ?? 'not_requested') as JomCheckStatus
    const jomcheckManualPending =
      isJomCheckManual() &&
      report.add_jomcheck &&
      jomcheckStatus !== 'success' &&
      jomcheckStatus !== 'failed'

    if (
      !isJomCheckManual() &&
      report.add_jomcheck &&
      jomcheckStatus !== 'success' &&
      jomcheckStatus !== 'failed'
    ) {
      const normPlate = normalisePlate(plate ?? '')
      setJomCheckStatus(report.id, 'pending').catch(() => {})
      try {
        const result = await lookupJomCheck(normPlate)
        if (result) {
          await setJomCheckSuccess(report.id, result)
          jomcheckData   = result
          jomcheckStatus = 'success'
        } else {
          await setJomCheckFailed(report.id, 'no_result')
          jomcheckStatus = 'failed'
        }
      } catch (err) {
        await setJomCheckFailed(report.id, String(err))
        jomcheckStatus = 'failed'
      }
    } else if (jomcheckStatus === 'success') {
      jomcheckData = report.jomcheck_data as JomCheckResult | null
    }

    // Market prices — serve from cache, refresh in background if stale
    let marketPrices: CachedMarketPrices | null = null
    if (vehicleData?.make && vehicleData?.model && vehicleData?.registrationYear) {
      const mk      = vehicleData.make as string
      const rawModel = vehicleData.model as string
      const yr      = vehicleData.registrationYear as string
      const desc    = (vehicleData.description as string) ?? ''

      const mo = buildMarketModelKeyword(rawModel, desc)

      marketPrices = await getCachedMarketPrices(mk, mo, yr).catch(() => null)
      if (!marketPrices) {
        const scrape = fetchAndCacheMarketPrices(mk, mo, yr).catch(() => {})
        await Promise.race([scrape, new Promise(r => setTimeout(r, 8_000))])
        marketPrices = await getCachedMarketPrices(mk, mo, yr).catch(() => null)
      }
    }

    return (
      <>
        <Nav />
        <Shell>
          <div className="pt-5 pb-6 space-y-5">
            <AnalyticsEvent event="report_page_viewed" properties={{ is_paid: true }} />
            {/* The human note leads. Everything below it is machine output a
                competitor could reproduce; this is the part that waited for a
                person, and it is what the price difference bought. */}
            <ReviewerNote note={report.reviewer_note} />
            {/* No page-level plate header — the report's own header card
                (plate + car + date) opens the document directly below */}
            {report.asking_price_rm == null && vehicleData && claimToken && (
              <AskingPriceForm checkId={params.checkId} claimToken={claimToken} />
            )}
            {!!vehicleData?.make && !marketPrices && (
              <div className="flex items-center gap-2 bg-[#F0FDF4] border border-[#BBF7D0] rounded-[12px] px-4 py-3">
                <div className="w-3.5 h-3.5 rounded-full border-2 border-[#BBF7D0] border-t-[#064E4A] animate-spin flex-shrink-0" />
                <p className="font-body text-[13px] text-[#374151]">Sedang mencari harga pasaran…</p>
              </div>
            )}
            <MarketPricePoller active={!!vehicleData?.make && !marketPrices} />
            <BuyerReportContent
              plate={carLabel}
              askingPriceRm={report.asking_price_rm ?? null}
              vehicleData={vehicleData}
              marketPrices={marketPrices}
              addJomCheck={report.add_jomcheck}
              jomcheckData={jomcheckData}
              jomcheckStatus={jomcheckStatus}
              jomcheckManualPending={jomcheckManualPending}
              generatedAt={report.created_at}
              claimedMileageKm={report.claimed_mileage_km}
              upsellJomCheck={
                process.env.JOMCHECK_ENABLED === 'true' && !report.add_jomcheck
                  ? { checkId: params.checkId, claimToken: claimToken ?? '' }
                  : null
              }
            />
            <ReportFeedback checkId={params.checkId} plate={carLabel} />
          </div>
        </Shell>
      </>
    )
  }

  // ── Unpaid — locked preview + payment form ────────────────────────────────
  // Require claim_token to pay (session-only users without claim_token can't pay)
  if (!claimToken) notFound()

  const isPlateFlow = searchParams.source === 'plate'

  return (
    <>
      <Nav />
      <Shell>
        <div className="pt-5 pb-6 space-y-5">
          <AnalyticsEvent event="report_page_viewed" properties={{ is_paid: false }} />
          <div>
            <p className="font-heading font-bold text-[11px] uppercase tracking-[.08em] text-[#064E4A] mb-1">
              Laporan untuk
            </p>
            <h1 className="font-heading font-extrabold text-[38px] tracking-tight text-[#111827] leading-none">
              {carLabel}
            </h1>
          </div>

          {/* Free teaser — proof the car was found, before asking for RM12 */}
          <VehiclePreviewTeaser checkId={params.checkId} claimToken={claimToken} />

          {/* Free price evidence BEFORE the ask. PlateCheckerForm promises
              that adding the asking price reveals whether the seller's price is
              fair; until now that number was only prefilled into checkout. This
              keeps the promise, and gives the ad path the same proof the model
              tab has always given away.

              The gate now renders that evidence and owns the ordering for BOTH
              branches below. The non-plate branch previously went straight from
              LockedReportPreview — a generic locked document, not this buyer's
              answer — to the payment form, which is the same defect /check/[id]
              had, one ternary away. */}
          <FreeResultGate
            checkId={params.checkId}
            claimToken={claimToken}
            valuationPath="plate_report"
            initialAskingPrice={
              searchParams.asking_price ? parseInt(searchParams.asking_price, 10) : undefined
            }
          >
            {isPlateFlow ? (
              <>
                {/* plate="" — the page header above already shows the plate;
                    the pitch's plate block is only load-bearing on /check/[id] */}
                <PaidReportCtaTracker checkId={params.checkId} hasFreeVerdict={true} />
                <BuyerReportPitch plate="" />
                <PaymentForm
                  checkId={params.checkId}
                  claimToken={claimToken}
                  valuationPath="plate_report"
                  defaultAskingPrice={searchParams.asking_price ? parseInt(searchParams.asking_price, 10) : undefined}
                />
                <CollapsibleSampleReport />
              </>
            ) : (
              <>
                <LockedReportPreview />
                <PaymentForm
                  checkId={params.checkId}
                  claimToken={claimToken}
                  valuationPath="plate_report"
                  defaultAskingPrice={searchParams.asking_price ? parseInt(searchParams.asking_price, 10) : undefined}
                />
              </>
            )}
          </FreeResultGate>
        </div>
      </Shell>
    </>
  )
}
