import { notFound }             from 'next/navigation'
import { historyUpgradeAvailable } from '@/lib/pricing'
export const dynamic = 'force-dynamic'
import { Nav }                  from '@/components/layout/Nav'
import { Shell }                from '@/components/layout/Shell'
import { getCheck }             from '@/lib/db/checks'
import { getBuyerReport, setVehicleApiData } from '@/lib/db/buyer-reports'
import { lookupJomCheck, normalisePlate, isJomCheckManual, type JomCheckResult, type JomCheckStatus } from '@/lib/jomcheck'
import { setJomCheckStatus, setJomCheckSuccess, setJomCheckFailed } from '@/lib/jomcheck/db'
import { BuyerReportContent }   from '@/components/report/BuyerReportContent'
import { PaymentForm }          from '@/components/report/PaymentForm'
import { LockedReportPreview }  from '@/components/report/LockedReportPreview'
import { CollapsibleSampleReport } from '@/components/report/CollapsibleSampleReport'
import { FreeResultGate }      from '@/components/report/FreeResultGate'
import { intakeMileageForCheck } from '@/lib/db/listing-intake'
import { UnderReviewNotice }   from '@/components/report/UnderReviewNotice'
import { UndeliverableNotice } from '@/components/report/UndeliverableNotice'
import { ReviewerNote }        from '@/components/report/ReviewerNote'
import { DecisionImpact }      from '@/components/report/DecisionImpact'
import { PaidReportCtaTracker } from '@/components/report/PaidReportCtaTracker'
import { BuyerReportPitch }     from '@/components/report/BuyerReportPitch'
import { VehiclePreviewTeaser } from '@/components/report/VehiclePreviewTeaser'
import { mayRenderReport, wasHumanReviewed } from '@/lib/report-release'
import { parseOverrides, applyOverrides, correctedCarLabel } from '@/lib/reviewed-overrides'
import { isAdminAuthenticated } from '@/lib/admin-auth'
import { decrypt }              from '@/lib/crypto'
import { createClient }         from '@/lib/supabase/server'
import { getOrFetchVehicleData }      from '@/lib/db/plate-lookups'
import { getValuationByNvic }         from '@/lib/db/vehicle-valuations'
import { getCachedMarketPrices,
         fetchAndCacheMarketPrices }  from '@/lib/db/market-prices'
import type { CachedMarketPrices }    from '@/lib/db/market-prices'
import { resolveCarIdentity }        from '@/lib/report-identity'
import { AnalyticsEvent }             from '@/components/layout/AnalyticsEvent'
import { AskingPriceForm }            from '@/components/report/AskingPriceForm'
import { MarketPricePoller }          from '@/components/report/MarketPricePoller'
import { ReportFeedback }             from '@/components/report/ReportFeedback'

interface Props {
  params:       { checkId: string }
  searchParams: { claim_token?: string; asking_price?: string; source?: string; admin_preview?: string }
}

export default async function BuyerReportPage({ params, searchParams }: Props) {
  const claimToken = searchParams.claim_token

  type CheckRow = NonNullable<Awaited<ReturnType<typeof getCheck>>>
  let row: CheckRow | null = null

  if (claimToken) {
    row = await getCheck(params.checkId, claimToken)
  }
  // Fallback: if claim_token lookup failed, try auth ownership check
  if (!row) {
    try {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const candidate = await getCheck(params.checkId)
        if (candidate?.check.user_id === user.id) row = candidate
      }
    } catch {
      // non-fatal
    }
  }

  if (!row || row.check.status !== 'complete') notFound()

  const report = await getBuyerReport(params.checkId)
  const isPaid = report?.status === 'paid'
  // Null when the buyer identified the car by brand/model/year (migration 032).
  // Every plate-dependent step below is skipped rather than faked: an empty
  // string here would render "plat " with nothing after it, and would send the
  // provider a lookup for the empty plate.
  const plateEnc = row.check.plate_encrypted
  const plate    = plateEnc ? decrypt(plateEnc as string).toUpperCase() : null
  // What the report calls this car when there is no plate to head it with.
  const carLabel = plate
    ?? [row.check.brand, row.check.model, row.check.year].filter(Boolean).join(' ')
    ?? ''

  // ── Paid, but no human has released it yet ────────────────────────────────
  //
  // THIS RETURNS EARLY ON PURPOSE. "Disemak oleh manusia sebelum dihantar" is
  // only true if an unreviewed report is unreachable, so BuyerReportContent is
  // not rendered hidden, not collapsed and not greyed out — it is never
  // mounted, and none of the work below it runs. Same rule FreeResultGate
  // already applies to the paywall, for the same reason: an ordering held by
  // JSX position is one hurried edit away from being untrue.
  //
  // The draft the reviewer reads is generated by /admin/review, not here.
  //
  // The reviewer is the ONE exception, and it is authenticated server-side.
  // `?admin_preview=1` alone does nothing: isAdminAuthenticated() compares an
  // httpOnly cookie holding sha256(ADMIN_SECRET) with timingSafeEqual, so the
  // flag is a routing hint and the cookie is the authority. Without this the
  // review queue would ask a human to approve a report they cannot read.
  const adminPreview = searchParams.admin_preview === '1' && isAdminAuthenticated()

  if (isPaid && report && !mayRenderReport(report) && !adminPreview) {
    // UNDELIVERABLE IS NOT "STILL WAITING".
    //
    // Both states are "paid, nothing released", so both used to land on
    // UnderReviewNotice — which repeats the 24-hour promise. For a report a
    // reviewer had already given up on, that screen kept promising a decision
    // that was never coming, to the one buyer Paqar had already let down. And
    // the refund guarantee that justifies the price arrived as an unexplained
    // bank transfer, if the buyer noticed it at all.
    const undeliverable = report.review_status === 'unable_to_complete'
    return (
      <>
        <Nav />
        <Shell>
          <AnalyticsEvent
            event="report_page_viewed"
            properties={{ is_paid: true, released: false, undeliverable }}
          />
          {undeliverable
            ? <UndeliverableNotice
                checkId={params.checkId}
                reason={report.reviewer_note ?? null}
                refundStatus={report.refund_status ?? null}
              />
            : <UnderReviewNotice checkId={params.checkId} />}
        </Shell>
      </>
    )
  }

  // ── Paid AND released — full report ───────────────────────────────────────
  if ((mayRenderReport(report) || (adminPreview && isPaid)) && report) {
    // WHAT THE REVIEWER CORRECTED, applied to what the buyer reads.
    //
    // reviewed_overrides used to be written on release and read by nothing, so
    // a reviewer could fix the price or the model, press release, and the buyer
    // received the uncorrected machine output under a note implying a human had
    // checked it. That is worse than having no correction feature: both parties
    // believe something untrue.
    const overrides     = parseOverrides(report.reviewed_overrides)
    const reviewed      = applyOverrides({
      overrides,
      askingPriceRm: report.asking_price_rm ?? null,
      mileageKm:     report.claimed_mileage_km ?? null,
    })
    const reviewedLabel = correctedCarLabel(overrides, {
      brand: row.check.brand, model: row.check.model, year: row.check.year,
    })
    // Lazy fetch: call VehicleAPI once, store in DB, serve from cache on subsequent views
    let vehicleData = report.vehicleapi_data as Record<string, unknown> | null ?? null
    if (!vehicleData) {
      const apiResult = plate ? await getOrFetchVehicleData(plate) : null
      if (apiResult) {
        const valuation = await getValuationByNvic(
          apiResult.nvic,
          { make: apiResult.make, year: apiResult.registrationYear, model: apiResult.model }
        ).catch(() => null)
        vehicleData = { ...apiResult, valuation: valuation ?? null }
        setVehicleApiData(report.id, vehicleData).catch(() => {}) // non-blocking
      }
    } else if ((vehicleData.valuation as Record<string, unknown> | null)?.familyFloorNewPrice === undefined) {
      // Heal pre-guard valuations: the old exact-NVIC lookup silently failed
      // on duplicate table rows and stored the CHEAPEST fallback variant
      // (a JCW GP frozen as a Clubman). Re-derive once with the fixed
      // lookup and persist; healed rows carry familyFloorNewPrice and skip this.
      const healed = await getValuationByNvic(
        (vehicleData.nvic as string) ?? '',
        {
          make:  (vehicleData.make as string) ?? '',
          year:  (vehicleData.registrationYear as string) ?? '',
          model: (vehicleData.model as string) ?? undefined,
        }
      ).catch(() => null)
      if (healed) {
        vehicleData = { ...vehicleData, valuation: healed }
        setVehicleApiData(report.id, vehicleData).catch(() => {}) // non-blocking
      }
    }

    // JomCheck — lazy lookup, cached after first success, never retried after failure.
    // In manual mode the API is never called: the owner keys results in via
    // /admin/jomcheck and the report shows a "sedang diproses" card until then.
    let jomcheckData:   JomCheckResult | null = null
    let jomcheckStatus: JomCheckStatus = (report.jomcheck_status ?? 'not_requested') as JomCheckStatus
    const jomcheckManualPending =
      isJomCheckManual() &&
      report.add_jomcheck &&
      jomcheckStatus !== 'success' &&
      jomcheckStatus !== 'failed'

    if (
      !isJomCheckManual() &&
      report.add_jomcheck &&
      jomcheckStatus !== 'success' &&
      jomcheckStatus !== 'failed'
    ) {
      const normPlate = normalisePlate(plate ?? '')
      setJomCheckStatus(report.id, 'pending').catch(() => {})
      try {
        const result = await lookupJomCheck(normPlate)
        if (result) {
          await setJomCheckSuccess(report.id, result)
          jomcheckData   = result
          jomcheckStatus = 'success'
        } else {
          await setJomCheckFailed(report.id, 'no_result')
          jomcheckStatus = 'failed'
        }
      } catch (err) {
        await setJomCheckFailed(report.id, String(err))
        jomcheckStatus = 'failed'
      }
    } else if (jomcheckStatus === 'success') {
      jomcheckData = report.jomcheck_data as JomCheckResult | null
    }

    // ── Market prices: THE SECTION THE BUYER ACTUALLY PAID FOR ──────────────
    //
    // This was gated on `vehicleData?.make`, i.e. on the plate lookup having
    // succeeded. Since migration 032 the plate is optional and plateless is the
    // DEFAULT journey, so for most buyers marketPrices stayed null and
    // "PERBANDINGAN HARGA" rendered as a heading with nothing under it. They
    // paid RM29 for comparable prices and received an empty section — while the
    // free coverage check, minutes earlier, had told them Paqar had enough ads
    // for this car. The two disagreed because they identified the car
    // differently.
    //
    // So the plate lookup is now a REFINEMENT, and the check row is the floor.
    // A registered make/model/description is better evidence when it exists —
    // it is what the car actually is rather than what the advert called it.
    //
    // The reviewer's corrections win over both. If a human changed the year
    // from 2019 to 2018, the comparables must be 2018 cars; pulling the
    // uncorrected cohort would quietly undo the correction the buyer paid for.
    const identity = resolveCarIdentity({ check: row.check, vehicleData, overrides })

    let marketPrices: CachedMarketPrices | null = null
    // Whether a background scrape is genuinely in flight. The spinner and the
    // poller below hang off THIS, not off the plate lookup: a car we never
    // identified has nothing coming, and a spinner promising otherwise would
    // run for ever on the page the buyer already paid for.
    let marketRefreshStarted = false
    {
      // ── THE SECTION THE BUYER ACTUALLY PAID FOR ─────────────────────────
      //
      // This was gated on the plate lookup having succeeded. Since migration
      // 032 the plate is optional and plateless is the DEFAULT journey, so for
      // most buyers marketPrices stayed null and "PERBANDINGAN HARGA" rendered
      // as a heading with nothing under it — while the free coverage check,
      // minutes earlier, had told them Paqar had enough ads for this car.
      //
      // resolveCarIdentity is shared with the reviewer's queue for exactly
      // that reason: a reviewer approving a decision computed from one cohort
      // while the buyer reads another is a failure neither of them can see.
      if (identity) {
        const { brand: mk, modelKeyword: mo, year: yr } = identity
        marketPrices = await getCachedMarketPrices(mk, mo, yr).catch(() => null)
        if (!marketPrices) {
          marketRefreshStarted = true
          const scrape = fetchAndCacheMarketPrices(mk, mo, yr).catch(() => {})
          await Promise.race([scrape, new Promise(r => setTimeout(r, 8_000))])
          marketPrices = await getCachedMarketPrices(mk, mo, yr).catch(() => null)
        }
      }
    }

    return (
      <>
        <Nav />
        <Shell>
          <div className="pt-5 pb-6 space-y-5">
            {/* A REVIEWER IS NOT A BUYER.
                Every paid report is opened here by whoever works the queue, via
                ?admin_preview=1. Firing the buyer's view event on those opens
                would put a reviewer hit on every single paid row — and since
                the experiment is measuring whether buyers come back to read the
                decision they paid for, that one event is the measurement.
                Suppressed rather than tagged: an is_admin property still has to
                be filtered by every future query that touches this event, and
                the one that forgets reports reviewer traffic as demand. */}
            {!adminPreview && (
              <AnalyticsEvent event="report_page_viewed" properties={{ is_paid: true, released: true }} />
            )}
            {/* The human note leads. Everything below it is machine output a
                competitor could reproduce; this is the part that waited for a
                person, and it is what the price difference bought. */}
            <ReviewerNote note={report.reviewer_note} humanReviewed={wasHumanReviewed(report)} />
            {/* No page-level plate header — the report's own header card
                (plate + car + date) opens the document directly below */}
            {report.asking_price_rm == null && vehicleData && claimToken && (
              <AskingPriceForm checkId={params.checkId} claimToken={claimToken} />
            )}
            {marketRefreshStarted && !marketPrices && (
              <div className="flex items-center gap-2 bg-[#F0FDF4] border border-[#BBF7D0] rounded-[12px] px-4 py-3">
                <div className="w-3.5 h-3.5 rounded-full border-2 border-[#BBF7D0] border-t-[#064E4A] animate-spin flex-shrink-0" />
                <p className="font-body text-[13px] text-[#374151]">Sedang mencari harga pasaran…</p>
              </div>
            )}
            <MarketPricePoller active={marketRefreshStarted && !marketPrices} />
            <BuyerReportContent
              plate={reviewedLabel ?? carLabel}
              plateSupplied={plate != null}
              reviewerDecision={overrides.finalDecision ?? null}
              reviewerNextAction={overrides.nextAction ?? null}
              reviewerSellerQuestions={overrides.sellerQuestions ?? null}
              cohortYear={identity?.year ?? null}
              cohortModel={identity?.model ?? null}
              cohortVariant={identity?.model ?? null}
              cohortBrand={identity?.brand ?? null}
              cohortMarket={identity?.market ?? 'used'}
              cohortVariantToken={identity?.variantToken ?? null}
              askingPriceRm={reviewed.askingPriceRm}
              vehicleData={vehicleData}
              marketPrices={marketPrices}
              addJomCheck={report.add_jomcheck}
              jomcheckData={jomcheckData}
              jomcheckStatus={jomcheckStatus}
              jomcheckManualPending={jomcheckManualPending}
              generatedAt={report.created_at}
              claimedMileageKm={reviewed.mileageKm}
              rollbackSuppressed={reviewed.suppressMileageWarning}
              upsellJomCheck={
                historyUpgradeAvailable() && !report.add_jomcheck
                  ? { checkId: params.checkId, claimToken: claimToken ?? '' }
                  : null
              }
            />
            {/* Below the report, never over it. A buyer who ignores this
                loses nothing — it is research, not a toll on what they paid
                for. */}
            <DecisionImpact checkId={params.checkId} revision={report.revision ?? 1} />
            <ReportFeedback checkId={params.checkId} plate={carLabel} />
          </div>
        </Shell>
      </>
    )
  }

  // ── Unpaid — locked preview + payment form ────────────────────────────────
  // Require claim_token to pay (session-only users without claim_token can't pay)
  if (!claimToken) notFound()

  // What the buyer already told us at intake. Asking twice is a second
  // question with a known answer, and two different answers give the reviewer
  // conflicting mileages for one car.
  const intakeMileageKm = await intakeMileageForCheck(params.checkId).catch(() => null)

  const isPlateFlow = searchParams.source === 'plate'

  return (
    <>
      <Nav />
      <Shell>
        <div className="pt-5 pb-6 space-y-5">
          <AnalyticsEvent event="report_page_viewed" properties={{ is_paid: false }} />
          <div>
            <p className="font-heading font-bold text-[11px] uppercase tracking-[.08em] text-[#064E4A] mb-1">
              Laporan untuk
            </p>
            <h1 className="font-heading font-extrabold text-[38px] tracking-tight text-[#111827] leading-none">
              {carLabel}
            </h1>
          </div>

          {/* Proof the car was found, before the ask — BUT ONLY IF THERE IS A
              PLATE TO FIND IT BY.
              Mounted unconditionally, it spent 24 seconds and 16 requests
              spinning "Mencari maklumat kenderaan…" on every plateless check,
              then landed on "Rekod kenderaan tidak dijumpai — sila semak semula
              nombor plat": telling a buyer to re-check a plate they never
              entered, at the top of the page where they are about to pay.
              Since migration 032 the plate is optional and plateless is the
              DEFAULT journey, so that was the majority experience.
              Nothing is lost by withholding it — the coverage card below already
              names the car Paqar matched. */}
          {plate && <VehiclePreviewTeaser checkId={params.checkId} claimToken={claimToken} />}

          {/* Free price evidence BEFORE the ask. PlateCheckerForm promises
              that adding the asking price reveals whether the seller's price is
              fair; until now that number was only prefilled into checkout. This
              keeps the promise, and gives the ad path the same proof the model
              tab has always given away.

              The gate now renders that evidence and owns the ordering for BOTH
              branches below. The non-plate branch previously went straight from
              LockedReportPreview — a generic locked document, not this buyer's
              answer — to the payment form, which is the same defect /check/[id]
              had, one ternary away. */}
          <FreeResultGate
            checkId={params.checkId}
            claimToken={claimToken}
            valuationPath="plate_report"
            initialAskingPrice={
              searchParams.asking_price ? parseInt(searchParams.asking_price, 10) : undefined
            }
          >
            {isPlateFlow ? (
              <>
                {/* plate="" — the page header above already shows the plate;
                    the pitch's plate block is only load-bearing on /check/[id] */}
                {/* false everywhere now — no surface shows a free verdict.
                    See PaidReportCtaTracker on why the prop stays. */}
                <PaidReportCtaTracker checkId={params.checkId} hasFreeVerdict={false} />
                <BuyerReportPitch plate="" />
                <PaymentForm
                  checkId={params.checkId}
                  claimToken={claimToken}
                  valuationPath="plate_report"
                  defaultAskingPrice={searchParams.asking_price ? parseInt(searchParams.asking_price, 10) : undefined}
                  defaultMileageKm={intakeMileageKm ?? undefined}
                />
                <CollapsibleSampleReport />
              </>
            ) : (
              <>
                {/* hasPlate gates the registration row: without a plate
                    there is no record to check, and promising one on the page
                    that asks for money is the claim this product can least
                    afford to get wrong. */}
                <LockedReportPreview hasPlate={plate != null} />
                <PaymentForm
                  checkId={params.checkId}
                  claimToken={claimToken}
                  valuationPath="plate_report"
                  defaultAskingPrice={searchParams.asking_price ? parseInt(searchParams.asking_price, 10) : undefined}
                  defaultMileageKm={intakeMileageKm ?? undefined}
                />
              </>
            )}
          </FreeResultGate>
        </div>
      </Shell>
    </>
  )
}
